Repository social-plan-it/plan-it-social-web, pull requests merged in 2023-08, with the labels that each got.

#40 Create login, signup components
  app/components/layout/footer.tsx
  app/components/layout/top-nav.tsx
  app/components/marketing/events-section.tsx
  app/components/marketing/hero-section.tsx
  app/components/ui/containers.tsx
  app/components/ui/forms.tsx
  app/components/ui/images.tsx
  app/components/ui/links.tsx
  app/root.tsx
  app/routes/_auth.login.tsx
  app/routes/_auth.logout.tsx
  app/routes/_auth.signup.tsx
  app/routes/_auth.tsx
  app/routes/_index.tsx
Labels: enhancement, UI components

#41 Implement loading indications (login, signup), improve layout (groups/new)
  app/routes/_auth.login.tsx
  app/routes/_auth.signup.tsx
  app/routes/group.new.tsx
  app/routes/groups.tsx
  app/routes/groups_.new.tsx
Labels: enhancement

#44 Header component
  app/components/ui/headers.tsx
  app/routes/groups_.new.tsx
Labels: enhancement

#46 Add Contributing md file
  CONTRIBUTING.md
Labels: documentation

#53 Jaycam/navbar redesign
  app/components/layout/top-nav.tsx
  app/components/marketing/hero-section.tsx
  app/root.tsx
Labels: UI components

#55 Reflect the user's logged in state in top nav
  app/components/layout/top-nav.tsx
Labels: bug, enhancement

#52 Jaycam/benefits section
  app/components/marketing/benefits-section.tsx
  app/routes/_index.tsx
Labels: UI components

#54 Add Data Loading Feature to EventsSection
  app/components/marketing/events-section.tsx
  app/routes/_index.tsx
  package-lock.json
  package.json
  prisma/schema.prisma
  prisma/seed.ts
Labels: enhancement

#58 Fix: UI shows logged in users logging out when navigating
  app/components/layout/top-nav.tsx
Labels: bug

#59 Auto format all files and add GitHub ESLint action
  .github/workflows/lint.yml
  README.md
  app/components/marketing/benefits-section.tsx
  app/entry.client.tsx
  app/entry.server.tsx
  app/root.tsx
  app/routes/_index.tsx
  package.json
  server.ts
Labels: dev environment

#61 Add zod validation to user sign up form
  app/modules/response/response.server.ts
  app/routes/_auth.signup.tsx
  package-lock.json
  package.json
Labels: enhancement, introduces new dependency
