Repository social-plan-it/plan-it-social-web, pull requests merged in 2023-07, with the labels that each got.

#31 Bump all Remix packages to the latest version
  .gitignore
  package-lock.json
  package.json
Labels: bug, dev environment

#37 Add user group event relationships to db schema
  prisma/schema.prisma
Labels: database model

#39 Add logout functionality and remove hardcoded SESSION_SECRET
  app/components/top-nav.tsx
  app/hooks/useCurrentUser.ts
  app/modules/session/session.server.ts
  app/root.tsx
  app/routes/logout.tsx
Labels: enhancement
