Repository social-plan-it/plan-it-social-web, pull requests merged in 2023-09, with the labels that each got.

#62 Add option to sign in with Google
  app/hooks/useEnv.ts
  app/modules/session/buttons.tsx
  app/modules/session/google-auth.server.ts
  app/root.tsx
  app/routes/_auth.login.tsx
  package-lock.json
  package.json
Labels: enhancement, introduces new dependency

#65 Add props to input component
  app/components/ui/forms.tsx
  app/routes/_auth.login.tsx
  app/routes/_auth.signup.tsx
  package-lock.json
  package.json
Labels: UI components

#66 Create reusable form input components
  app/components/ui/containers.tsx
  app/components/ui/forms.tsx
  app/routes/groups_.new.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: enhancement, introduces new dependency

#67 Update Remix to v2 and other dependencies
  app/entry.server.tsx
  package-lock.json
  package.json
  remix.config.js
  server.ts
Labels: dev environment
