Repository social-plan-it/plan-it-social-web, pull requests merged in 2024-03, with the labels that each got.

#123 Add storybook for UI components, migrate Remix to vite
  .eslintrc.cjs
  .gitignore
  .prettierrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  app/root.tsx
  env.d.ts
  package-lock.json
  package.json
  postcss.config.mjs
  remix.config.js
  stories/Button.stories.ts
  stories/Button.tsx
  storybook.vite.config.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement, UI components

#126 Enhance button story with arg types
  app/components/ui/button.tsx
  stories/Button.stories.ts
  stories/Button.tsx
Labels: documentation, UI components

#133 Implement Sign In With Passkey
  .github/workflows/playwright.yml
  app/modules/session/webauthn.server.ts
  app/routes/_auth.generate-authentication-options.ts
  app/routes/_auth.login.tsx
  app/routes/settings.tsx
  package-lock.json
  package.json
  prisma/schema.prisma
  prisma/seed.ts
Labels: enhancement, dev environment, introduces new dependency, database model
